export const missions = {
  assualt: {
    type: [
      "People.",
      "The Wild.",
      "Undead.",
      "Undead.",
      "Powerful Undead.",
      "Powerful Undead.",
    ],
    rewards: [
      "+2 Morale.",
      "+3 Morale.",
      "+4 Morale.",
      "+2 Morale. +1 Support.",
      "+2 Morale. +1 Intel.",
      "+2 Morale. -1 Time.",
    ],
    penalties: [
      "+1 Pressure. +1 Time.",
      "+1 Time.",
      "-1 Supply.",
      "+1 Pressure.",
      "+1 Pressure.",
      "+1 Pressure.",
    ],
  },
  recon: {
    type: [
      "Area Recon.",
      "Route Recon.",
      "Troop Recon.",
      "Infiltration.",
      "Exfiltration.",
      "Pick above + Danger.",
    ],
    rewards: [
      "+2 Intel.",
      "+2 Intel.",
      "Asset. +1 Intel.",
      "Asset or Troops. +1 Intel.",
      "+1 Intel. -1 Time.",
      "+3 Intel.",
    ],
    penalties: [
      "+1 Time.",
      "2 Deaths.",
      "1 Death.",
      "+1 Pressure.",
      "+1 Pressure.",
      "None.",
    ],
  },
  religious: {
    type: [
      "Escort.",
      "Cleansing.",
      "Defense.",
      "Unearth.",
      "Pick Above + Favor.",
      "Pick Above + Favor.",
    ],
    rewards: [
      "-1 Time. + 2 xp.",
      "+2 Morale. +10 Points.",
      "+1 Intel. +2 Morale.",
      "Fine Asset.",
      "Exceptional Asset.",
      "Specialist.",
    ],
    penalties: [
      "-1 Morale. +1 Pressure.",
      "+1 Pressure.",
      "+1 Pressure.",
      "-1 Morale.",
      "-1 Morale.",
      "None.",
    ],
  },
  supply: {
    type: [
      "Scrounge or Trade.",
      "Scrounge or Trade.",
      "Rescue Supplies.",
      "Rescue Supplies.",
      "Mercenary Work.",
      "Mercenary Work.",
    ],
    rewards: [
      "Asset. +1 Supply.",
      "Asset. +1 Supply.",
      "+2 Supply.",
      "Asset. +2 Supply.",
      "+3 Supply.",
      "+3 Supply.",
    ],
    penalties: [
      "-1 Morale. -1 Supply.",
      "-1 Supply.",
      "-1 Morale.",
      "-1 Morale",
      "None.",
      "None.",
    ],
  },
};
